//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsureFlowAI.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CarouselItems
    {
        public int ID { get; set; }
        public string WelcomeText { get; set; }
        public string Headline { get; set; }
        public string SubHeadline { get; set; }
        public string ImageUrl { get; set; }
    }
}
