//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsureFlowAI.DAL.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_About
    {
        public int ID { get; set; }
        public string SectionHeading { get; set; }
        public string Paragraph1 { get; set; }
        public string Paragraph2 { get; set; }
        public string ImageUrl { get; set; }
        public string Vision { get; set; }
        public string Mission { get; set; }
        public string Value { get; set; }
    }
}
